baseURL = "https://test-result.kojiisd.tk/"
languageCode = "en-us"
title = "TESTS RESULT"

[blackfriday]
  angledQuotes = true
  extensions = ["hardLineBreak"]
  fractions = false
  plainIDAnchors = true

[params]
  customCSS = ["css/custom.css"]